logging:
  level:
    root: DEBUG
spring:
  application:
    name: STUDENT_API
  profiles.actives: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddlAuto: update
  h2:
    console.enabled: true

server:
  port: 8091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true